import os
import base64
import json
from PIL import Image, ImageDraw

# Input and output paths
src_dir = "/Users/paulgibeault/.gemini/antigravity/brain/439d6062-9f51-4c10-ba91-147a65f6c6dc"
dest_dir = "/Users/paulgibeault/work/sow-duku/assets"

# Files generated by generate_image
files = {
    "favicon": "favicon_new_1783004321844.png",
    "wordmark": "logo_wordmark_1783003436171.png",
    "logo_square": "logo_square_1783003446975.png",
    "piggy": "piggy_settled_1783003456228.png",
    "hoofprint": "hoofprint_solid_1783005168720.png",
    "hearts": "hearts_pair_1783003478437.png",
    # Phase 2 illustrations
    "win_vignette": "win_vignette_1783005683388.png",
    "fail_vignette": "fail_vignette_1783005696121.png",
    "empty_history": "empty_history_1783005712131.png",
    "empty_curated": "empty_curated_1783005723971.png",
    "empty_firstrun": "empty_firstrun_1783005738258.png",
    "misty_badge": "misty_badge_1783005750557.png"
}

def remove_background(img, seed_points, thresh=40):
    """
    Converts image to RGBA and flood-fills from seed_points to make background transparent.
    """
    rgba = img.convert("RGBA")
    # Apply floodfill for each seed point to clear background
    for pt in seed_points:
        ImageDraw.floodfill(rgba, pt, (0, 0, 0, 0), thresh=thresh)
    return rgba

def crop_with_padding(img, bbox, padding=20):
    """
    Crops the image to bbox with an added padding on all sides.
    """
    left, top, right, bottom = bbox
    left = max(0, left - padding)
    top = max(0, top - padding)
    right = min(img.width, right + padding)
    bottom = min(img.height, bottom + padding)
    return img.crop((left, top, right, bottom))

def save_as_svg(img, filename):
    """
    Saves a PIL Image as an SVG file containing a base64 encoded PNG.
    """
    # First save PIL image as PNG bytes in memory
    import io
    png_bio = io.BytesIO()
    img.save(png_bio, format="PNG")
    png_data = png_bio.getvalue()
    b64_str = base64.b64encode(png_data).decode("utf-8")
    
    width, height = img.size
    svg_content = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">
  <image href="data:image/png;base64,{b64_str}" width="{width}" height="{height}"/>
</svg>'''
    
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w") as f:
        f.write(svg_content)
    print(f"Saved SVG: {filename} ({width}x{height})")

def process_all():
    # 1. Process Favicon
    fav_src_path = os.path.join(src_dir, files["favicon"])
    if os.path.exists(fav_src_path):
        fav_img = Image.open(fav_src_path)
        # Crop to the piglet circle bounding box with a small margin so it fills the icon space
        fav_img = fav_img.crop((264, 192, 728, 656))
        os.makedirs(os.path.join(dest_dir, "favicon"), exist_ok=True)
        
        # Save PNG resolutions
        sizes = [512, 192, 180, 32, 16]
        for sz in sizes:
            resized = fav_img.resize((sz, sz), Image.Resampling.LANCZOS)
            name = f"favicon-{sz}x{sz}.png" if sz != 180 else "apple-touch-icon.png"
            resized.save(os.path.join(dest_dir, "favicon", name), format="PNG")
            print(f"Saved favicon: {name}")
            
        # Create .ico file bundling 16, 32, 48
        ico_sizes = [16, 32, 48]
        ico_images = [fav_img.resize((sz, sz), Image.Resampling.LANCZOS) for sz in ico_sizes]
        ico_images[0].save(os.path.join(dest_dir, "favicon", "favicon.ico"), format="ICO", sizes=[(sz, sz) for sz in ico_sizes], append_images=ico_images[1:])
        print("Saved favicon.ico")

    # 2. Process Logo Wordmark
    wordmark_path = os.path.join(src_dir, files["wordmark"])
    if os.path.exists(wordmark_path):
        img = Image.open(wordmark_path)
        rgba = remove_background(img, [(0, 0), (0, 1023), (1023, 0), (1023, 1023)], thresh=40)
        bbox = rgba.getbbox()
        if bbox:
            rgba = crop_with_padding(rgba, bbox, padding=15)
        save_as_svg(rgba, os.path.join(dest_dir, "logo", "wordmark.svg"))
        
    # 3. Process Logo Square Variant
    square_path = os.path.join(src_dir, files["logo_square"])
    if os.path.exists(square_path):
        img = Image.open(square_path)
        rgba = remove_background(img, [(0, 0), (0, 1023), (1023, 0), (1023, 1023)], thresh=40)
        bbox = rgba.getbbox()
        if bbox:
            rgba = crop_with_padding(rgba, bbox, padding=15)
        save_as_svg(rgba, os.path.join(dest_dir, "logo", "mark-square.svg"))

    # 4. Process Settled Piggy
    pig_path = os.path.join(src_dir, files["piggy"])
    if os.path.exists(pig_path):
        img = Image.open(pig_path)
        # Crop out the peach outer border first
        cropped = img.crop((134, 134, 890, 890)).convert("RGBA")
        # Floodfill the white background of the cropped image
        rgba_pig = remove_background(cropped, [(0, 0)], thresh=40)
        bbox = rgba_pig.getbbox()
        if bbox:
            rgba_pig = crop_with_padding(rgba_pig, bbox, padding=20)
        save_as_svg(rgba_pig, os.path.join(dest_dir, "piggy", "settled.svg"))

    # 5. Process Hoofprint
    hoof_path = os.path.join(src_dir, files["hoofprint"])
    if os.path.exists(hoof_path):
        img = Image.open(hoof_path)
        rgba = remove_background(img, [(0, 0), (0, 1023), (1023, 0), (1023, 1023)], thresh=40)
        bbox = rgba.getbbox()
        if bbox:
            rgba = crop_with_padding(rgba, bbox, padding=20)
        save_as_svg(rgba, os.path.join(dest_dir, "board", "hoofprint.svg"))

    # 6. Process Hearts (Full & Empty)
    hearts_path = os.path.join(src_dir, files["hearts"])
    if os.path.exists(hearts_path):
        img = Image.open(hearts_path)
        width, height = img.size
        left_half = img.crop((0, 0, width // 2, height))
        right_half = img.crop((width // 2, 0, width, height))
        
        # Process Full Heart
        rgba_full = remove_background(left_half, [(0, 0)], thresh=40)
        bbox_full = rgba_full.getbbox()
        if bbox_full:
            rgba_full = crop_with_padding(rgba_full, bbox_full, padding=15)
        save_as_svg(rgba_full, os.path.join(dest_dir, "board", "heart-full.svg"))
        
        # Process Empty Heart
        rgba_empty = remove_background(right_half, [(0, 0)], thresh=40)
        bbox_empty = rgba_empty.getbbox()
        if bbox_empty:
            rgba_empty = crop_with_padding(rgba_empty, bbox_empty, padding=15)
        save_as_svg(rgba_empty, os.path.join(dest_dir, "board", "heart-empty.svg"))

    # ---- Phase 2 illustrations ----
    
    # 8. Win Vignette
    win_path = os.path.join(src_dir, files["win_vignette"])
    if os.path.exists(win_path):
        img = Image.open(win_path)
        rgba = remove_background(img, [(0, 0)], thresh=35)
        bbox = rgba.getbbox()
        if bbox:
            rgba = crop_with_padding(rgba, bbox, padding=20)
        save_as_svg(rgba, os.path.join(dest_dir, "illustration", "win-vignette.svg"))
        
    # 9. Fail Vignette
    fail_path = os.path.join(src_dir, files["fail_vignette"])
    if os.path.exists(fail_path):
        img = Image.open(fail_path)
        rgba = remove_background(img, [(0, 0)], thresh=35)
        bbox = rgba.getbbox()
        if bbox:
            rgba = crop_with_padding(rgba, bbox, padding=20)
        save_as_svg(rgba, os.path.join(dest_dir, "illustration", "fail-vignette.svg"))

    # 10. Empty History
    hist_path = os.path.join(src_dir, files["empty_history"])
    if os.path.exists(hist_path):
        img = Image.open(hist_path)
        rgba = remove_background(img, [(0, 0)], thresh=35)
        bbox = rgba.getbbox()
        if bbox:
            rgba = crop_with_padding(rgba, bbox, padding=20)
        save_as_svg(rgba, os.path.join(dest_dir, "illustration", "empty-history.svg"))

    # 11. Empty Curated
    cur_path = os.path.join(src_dir, files["empty_curated"])
    if os.path.exists(cur_path):
        img = Image.open(cur_path)
        rgba = remove_background(img, [(0, 0)], thresh=35)
        bbox = rgba.getbbox()
        if bbox:
            rgba = crop_with_padding(rgba, bbox, padding=20)
        save_as_svg(rgba, os.path.join(dest_dir, "illustration", "empty-curated.svg"))

    # 12. Empty First Run
    first_path = os.path.join(src_dir, files["empty_firstrun"])
    if os.path.exists(first_path):
        img = Image.open(first_path)
        rgba = remove_background(img, [(0, 0)], thresh=35)
        bbox = rgba.getbbox()
        if bbox:
            rgba = crop_with_padding(rgba, bbox, padding=20)
        save_as_svg(rgba, os.path.join(dest_dir, "illustration", "empty-firstrun.svg"))

    # 13. Misty Morning Badge
    misty_path = os.path.join(src_dir, files["misty_badge"])
    if os.path.exists(misty_path):
        img = Image.open(misty_path)
        # Crop out outer border first (212, 212, 812, 812)
        cropped = img.crop((212, 212, 812, 812)).convert("RGBA")
        rgba = remove_background(cropped, [(0, 0)], thresh=35)
        bbox = rgba.getbbox()
        if bbox:
            rgba = crop_with_padding(rgba, bbox, padding=15)
        save_as_svg(rgba, os.path.join(dest_dir, "illustration", "misty-badge.svg"))

    # 7. Generate site.webmanifest
    manifest = {
        "name": "Sowdoku",
        "short_name": "Sowdoku",
        "icons": [
            {
                "src": "favicon-192x192.png",
                "sizes": "192x192",
                "type": "image/png",
                "purpose": "any"
            },
            {
                "src": "favicon-512x512.png",
                "sizes": "512x512",
                "type": "image/png",
                "purpose": "any"
            }
        ],
        "theme_color": "#f4eee1",
        "background_color": "#f4eee1",
        "display": "standalone",
        "start_url": "../../index.html"
    }
    manifest_path = os.path.join(dest_dir, "favicon", "site.webmanifest")
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"Generated manifest: {manifest_path}")

if __name__ == "__main__":
    process_all()
